//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryProjectMvc.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Books()
        {
            this.RevisedStatus = false;
            this.Actions = new HashSet<Actions>();
        }
    
        public int BookId { get; set; }
        public string BookName { get; set; }
        public Nullable<byte> CategoryId { get; set; }
        public Nullable<int> AuthorId { get; set; }
        public string YearOfPublication { get; set; }
        public string Publisher { get; set; }
        public string Page { get; set; }
        public Nullable<bool> BookStatus { get; set; }
        public string BookPhoto { get; set; }
        public Nullable<bool> RevisedStatus { get; set; }
        public string CategoryForNet { get; set; }
        public string AuthorForNet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actions> Actions { get; set; }
        public virtual Authors Authors { get; set; }
        public virtual Categories Categories { get; set; }
    }
}
