//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryProjectMvc.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LibraryProjectEntities : DbContext
    {
        public LibraryProjectEntities()
            : base("name=LibraryProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actions> Actions { get; set; }
        public virtual DbSet<Authors> Authors { get; set; }
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Penalties> Penalties { get; set; }
        public virtual DbSet<Safes> Safes { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Abouts> Abouts { get; set; }
        public virtual DbSet<Contacts> Contacts { get; set; }
        public virtual DbSet<EducationStatuses> EducationStatuses { get; set; }
    
        public virtual ObjectResult<string> AuthorMostBook()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("AuthorMostBook");
        }
    
        public virtual ObjectResult<PublisherMostBook_Result> PublisherMostBook()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PublisherMostBook_Result>("PublisherMostBook");
        }
    
        public virtual ObjectResult<string> PublisherMostBookk()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PublisherMostBookk");
        }
    
        public virtual ObjectResult<string> UserMostBook()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UserMostBook");
        }
    
        public virtual ObjectResult<string> BookMostBooks()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("BookMostBooks");
        }
    
        public virtual ObjectResult<string> EmployeeMostActions()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("EmployeeMostActions");
        }
    }
}
